# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'db0d59bf-ac7d-4d67-8257-3eebc230bc55'
  imageRepository: 'vproapp'
  containerRegistry: 'akspractice01.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vpro-app/docker-compose.yaml'
  tag: '$(Build.BuildId)'

   # Agent VM image name
  Name: devops-agent-01

stages:
- stage: Build
  displayName: 'Vpro-App Build'
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: $(Name)
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'Sonar-Connection'
        scannerMode: 'Other'
    - task: CmdLine@2
      displayName: 'MVN Build'
      inputs:
        script: |
          mvn install
        workingDirectory: '$(Build.SourcesDirectory)/vpro-app/Code'     
    - task: CmdLine@2
      displayName: 'MVN Test'
      inputs:
        script: |
          mvn test && 
          mvn checkstyle:checkstyle
        workingDirectory: '$(Build.SourcesDirectory)/vpro-app/Code'
    - task: Maven@4
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/vpro-app/Code/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'Maven-Unit-Test'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
        checkStyleRunAnalysis: true
    - task: SonarQubeAnalyze@5
      inputs:
        jdkversion: 'JAVA_HOME_11_X64'
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'
    - task: DockerCompose@0
      displayName: 'DockerCompose-build'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'aks-rg-connection'
        azureContainerRegistry: 'akspractice01.azurecr.io'
        dockerComposeFile: '$(dockerfilePath)'
        projectName: 'vpro-app'
        action: 'Build services'
        includeSourceTags: true
        additionalImageTags: $(Build.BuildId)
    - task: DockerCompose@0
      displayName: 'DockerCompose-push'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'aks-rg-connection'
        azureContainerRegistry: '{"loginServer":"akspractice01.azurecr.io", "id" : "/subscriptions/410c1a95-68f7-4b30-9fdc-964a1658482d/resourceGroups/AKS-Practice/providers/Microsoft.ContainerRegistry/registries/akspractice01"}'
        dockerComposeFile: '$(dockerfilePath)'
        projectName: 'vpro-app'
        action: 'Push services'
        includeSourceTags: true
        additionalImageTags: $(Build.BuildId)